# 网站标题
baseURL = "https://kingpo.vercel.app/"
title = "六月长河"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言，仅在这里 CN 大写
languageCode = "zh-CN"
#字数统计计入中文

# 是否包括中日韩文字
hasCJKLanguage = true

enableEmoji = true
# nableGitInfo = true
enableRobotsTXT = true

relativeURLs = false
summaryLength = 150

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FixIt"

# Post frontmatter config
[frontmatter]
lastmod = [":git", "lastmod", ":fileModTime", ":defalut"]

[params]
#  FixIt 主题版本
version = "0.2.X"
# 网站描述
description = ""
# 网站关键词
keywords = ["charlie-King", "六月长河", "六月长河的博客", "Kingpo", "hugo"]
# 网站默认主题样式 ("light", "dark", "auto")
defaultTheme = "auto"
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
gitRepo = ""
#  哪种哈希函数用来 SRI, 为空时表示不使用 SRI
# ("sha256", "sha384", "sha512", "md5")
fingerprint = ""
#  日期格式
dateFormat = "2006-01-02"
# 网站图片，用于 Open Graph 和 Twitter Cards
images = ["/logo.png"]
#  开启 PWA 支持
enablePWA = true
#  是否自动显示外链图标
externalIcon = false
#  默认情况下，FixIt 只会在主页的 HTML 头中注入主题元标记。
# 您可以将其关闭，但如果您不这样做，我们将不胜感激，因为这是观察 FixIt 受欢迎程度上升的好方法。
disableThemeInject = false

#  应用图标配置
[params.app]
# 当添加到 iOS 主屏幕或者 Android 启动器时的标题，覆盖默认标题
title = "六月长河"
# 是否隐藏网站图标资源链接
noFavicon = false
# 更现代的 SVG 网站图标，可替代旧的 .png 和 .ico 文件
svgFavicon = ""
# Safari 图标颜色
iconColor = "#5bbad5"
# Windows v8-10 磁贴颜色
tileColor = "#da532c"
#  Android 浏览器主题色
[params.app.themeColor]
dark = "#252627"
light = "#ffffff"

#  搜索配置
[params.search]
enable = true
# 搜索引擎的类型 ("lunr", "algolia")
type = "algolia"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
#  最大结果数目
maxResultLength = 10
#  结果内容片段长度
snippetLength = 50
#  搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
#  是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false
[params.search.algolia]
appID = "B6R922P6DD" 
index = "dev_hugo" 
searchKey = "65d9478dcc1a7a885ab0286fc7721433" #在API Keys上拿到Search-Only API Key作为searchKey和Application ID作为appID

# 页面头部导航栏配置
[params.header]
#  桌面端导航栏模式 ("sticky", "normal", "auto")
desktopMode = "sticky"
#  移动端导航栏模式 ("sticky", "normal", "auto")
mobileMode = "auto"
#  页面头部导航栏标题配置
[params.header.title]
# LOGO 的 URL
logo = ""
# 标题名称
name = "六月长河"
# 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
pre = ""
# 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
post = ""
#  是否为标题显示打字机动画
typeit = true
#  页面头部导航栏副标题配置
[params.header.subtitle]
# 副标题名称
name = "的文字世界"
# 是否为副标题显示打字机动画
typeit = false

# 页面底部信息配置
[params.footer]
enable = true
#  自定义内容（支持 HTML 格式）
custom = ''
#  是否显示 Hugo 和主题信息
hugo = false
#  是否显示版权信息
copyright = true
#  是否显示作者
author = true
# 网站创立年份
since = 2022
#  网站创立时间
siteTime = '2022-07-13T19:30:34+08:00' # 例：'2019-02-03T19:30:34+08:00'
#  是否显示网站内容总字数
wordCount = true
#  公网安备信息，仅在中国使用（支持 HTML 格式）
gov = ""
#  ICP 备案信息，仅在中国使用（支持 HTML 格式）
icp = ""
# 许可协议信息（支持 HTML 格式）
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

#  Section（所有文章）页面配置
[params.section]
# section 页面每页显示文章数量
paginate = 20
# 日期格式（月和日）
dateFormat = "01-02"
# RSS 文章数目
rss = 20
#  最近更新文章设置
[params.section.recentlyUpdated]
days = 30
enable = true
maxCount = 10
rss = true

#  List（目录或标签）页面配置
[params.list]
# list 页面每页显示文章数量
paginate = 20
# 日期格式（月和日）
dateFormat = "01-02"
# RSS 文章数目
rss = 10

# 主页配置
[params.home]
#  RSS 文章数目
rss = 20
# 主页个人信息
[params.home.profile]
enable = true
#  选择使用 Gravatar 源站或其他镜像站，若留空则为默认的 "www.gravatar.com"
#   参数 `home.profile.gravatarSite` 自 v0.2.14 起已弃用，请改用 `gravatar.host`
# gravatarSite = ""
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = ""
# 主页显示头像的 URL
avatarURL = "/images/avatar.png"
#  主页显示的网站标题（支持 HTML 格式）
title = "Kingpo's Note"
# 主页显示的网站副标题
subtitle = "桃李春风一杯酒，江湖夜雨十年灯。"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
#  免责声明（支持 HTML 格式）
disclaimer = ""
# 主页文章列表
[params.home.posts]
enable = true
# 主页每页显示文章数量
paginate = 10

# 作者的社交信息设置
[params.social]

Bilibili = "toolkz"
Douban = "81104029"
Email = "zhjin66@qq.com"
GitHub = "charlie-king"
Weibo = "2296265347"
Zhihu = "xiao-bo-88-88"

Bandcamp = ""
Bitbucket = ""
Codepen = ""
Facebook = ""
Fivehundredpx = ""
Flickr = ""
Foursquare = ""
FreeCodeCamp = ""

Gitlab = ""
Goodreads = ""
Hackernews = ""
Instagram = ""
Keybase = ""
Kickstarter = ""
Lastfm = ""
Linkedin = ""
Medium = ""
Mix = ""
Odnoklassniki = ""
Patreon = ""
Paypal = ""
Pinterest = ""
Quora = ""
Reddit = ""
Skype = ""
Snapchat = ""
Soundcloud = ""
Spotify = ""
Stackoverflow = ""
Steam = ""
Strava = ""
Telegram = ""
Tumblr = ""
Twitch = ""
Twitter = ""
VK = ""

Whatsapp = ""
Xing = ""
Youtubechannel = ""
Youtubecustom = ""
Youtubelegacy = ""

Angellist = ""
Behance = ""
Deviantart = ""
Devto = ""
Dribbble = ""
Gitea = ""
Googlescholar = ""
Jsfiddle = ""
Mastodon = ""
Matrix = ""
Researchgate = ""
Slidershare = ""
Thingiverse = ""
Vine = ""
Wordpress = ""
XMPP = ""
# ORCID, ... , CSDN 
BuyMeaCoffee = ""
CSDN = ""
Diaspora = ""

Ko-Fi = "" 
Liberapay = "" 
Linktree = "" 
ORCID = "" 
QQ = "" 
QQGroup = "" # https://qun.qq.com/join.html
RSS = true # 

#  文章页面配置
[params.page]
#  是否在主页隐藏一篇文章
hiddenFromHomePage = false
#  是否在搜索结果中隐藏一篇文章
hiddenFromSearch = false
#  是否使用 twemoji
twemoji = true
# 是否使用 lightgallery
lightgallery = true
#  是否使用 ruby 扩展语法
ruby = true
#  是否使用 fraction 扩展语法
fraction = true
#  是否使用 fontawesome 扩展语法
fontawesome = true
# 许可协议信息（支持 HTML 格式）
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
# 是否在文章页面显示原始 Markdown 文档链接
linkToMarkdown = true
#  是否在 RSS 中显示全文内容
rssFullText = false
#  页面样式 ("narrow", "normal", "wide", ...)
pageStyle = "narrow"
#  强制使用 Gravatar 作为作者头像
gravatarForce = false
#  转载配置
[params.page.repost]
enable = false
url = ""
#  目录配置
[params.page.toc]
# 是否使用目录
enable = true
#  是否保持使用文章前面的静态目录
keepStatic = false
# 是否使侧边目录自动折叠展开
auto = true
#  目录位置 ("left", "right")
position = "right"
#  在文章开头显示提示信息，提醒读者文章内容可能过时
[params.page.expirationReminder]
enable = true
# 如果文章最后更新于这天数之前，显示提醒
reminder = 180
# 如果文章最后更新于这天数之前，显示警告
warning = 180
# 如果文章到期是否关闭评论
closeComment = false
#  代码配置
[params.page.code]
# 是否显示代码块的复制按钮
copy = true
#  是否显示代码块的编辑按钮
edit = true
# 默认展开显示的代码行数
maxShownLines = 20
#  文章编辑
[params.page.edit]
enable = false
# url = "https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name" # Link for fork & edit
url = "" # Link for fork & edit
#  KaTeX 数学公式 (https://katex.org)
[params.page.math]
enable = true
# 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# 默认行内定界符是 $ ... $ 和 \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX 插件 copy_tex
copyTex = true
# KaTeX 插件 mhchem
mhchem = true
#  Mapbox GL JS 配置 (https://docs.mapbox.com/mapbox-gl-js)
[params.page.mapbox]
# Mapbox GL JS 的 access token
accessToken = ""
# 浅色主题的地图样式
lightStyle = "mapbox://styles/mapbox/light-v9"
# 深色主题的地图样式
darkStyle = "mapbox://styles/mapbox/dark-v9"
# 是否添加 NavigationControl
navigation = true
# 是否添加 GeolocateControl
geolocate = true
# 是否添加 ScaleControl
scale = true
# 是否添加 FullscreenControl
fullscreen = true
#  文章页面的分享信息设置
[params.page.share]
Baidu = true
Blogger = false
Buffer = false
Digg = false
Evernote = true
Facebook = false
Flipboard = false
HackerNews = false
Instapaper = false
Line = false
Linkedin = false
Mix = false
Myspace = false
Odnoklassniki = false
Pinterest = false
Pocket = false
Reddit = false
Renren = false
Skype = false
Stumbleupon = false
Trello = false
Tumblr = false
Twitter = false
VK = false
Weibo = true
Whatsapp = false
Xing = false
enable = true
#  评论系统设置
[params.page.comment]
enable = true
# Valine 评论系统设置 (https://github.com/xCss/Valine)
[params.page.comment.valine]
appId = "fBVoqMFU1xet9Og99sfzU2Pu-MdYXbMMI"
appKey = "tdTYEKQLqjlE8Mh6tmCs2Vtz"
avatar = "/images/avatar.jpg"
enable = true
enableQQ = true
highlight = true
lang = "zh-CN"
meta = ['nick', 'mail', 'link']
pageSize = 10
placeholder = "欢迎留言交流！匿名昵称留空即可，留下的邮箱和网址可以更方便联系到你。"
recordIP = true
serverURLs = "https://fbvoqmfu.api.lncldglobal.com"
visitor = true
#  emoji 数据文件名称，默认是 "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# 位于 "themes/FixIt/assets/data/emoji/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件：
# "assets/data/emoji/"
commentCount = true # 
emoji = "" 

#  Artalk 评论系统设置 (https://artalk.js.org/)
[params.page.comment.artalk]
editorTravel = true
enable = false
flatMode = 'auto'
maxNesting = 3
noComment = ""
placeholder = ""
sendBtn = ""
server = "https://yourdomain/api/"
site = "默认站点"
# 当 `params.page.lightgallery` 启用时生效
lightgallery = false 
locale = "" # 
#  Disqus 评论系统设置 (https://disqus.com)
[params.page.comment.disqus]
enable = false
# Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
shortname = ""
#  Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
[params.page.comment.gitalk]
clientId = ""
clientSecret = ""
enable = false
owner = ""
repo = ""

#  Waline 评论系统设置 (https://waline.js.org)
[params.page.comment.waline]
comment = false # 
emoji = ['//unpkg.com/@waline/emojis@1.0.1/weibo'] 
enable = false 
highlighter = true # 
imageUploader = false # 
login = 'enable' 
meta = ['nick', 'mail', 'link'] 
pageSize = 10 
pageview = false # 
requiredMeta = [] 
serverURL = "" 
wordLimit = 0 
# visitor = false #  更名为 pageview
# uploadImage = false #  更名为 imageUploader
# highlight = true #  更名为 highlighter
# mathTagSupport = false 
# commentCount = false  更名为 comment
# Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
[params.page.comment.facebook]
appId = ""
enable = false
languageCode = "zh_CN"
numPosts = 10
width = "100%"
#  Telegram Comments 评论系统设置 (https://comments.app)
[params.page.comment.telegram]
color = ""
colorful = true
dislikes = false
enable = false
height = ""
limit = 5
outlined = false
siteID = ""
#  Commento 评论系统设置 (https://commento.io)
[params.page.comment.commento]
enable = false
#  Utterances 评论系统设置 (https://utteranc.es)
[params.page.comment.utterances]
enable = false
# owner/repo
darkTheme = "github-dark"
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
repo = ""
#  Twikoo 评论系统设置 (https://twikoo.js.org/)
[params.page.comment.twikoo]
commentCount = true
enable = false
envId = ""
path = ""
region = ""
visitor = true
# 当 `params.page.lightgallery` 启用时生效
lightgallery = false
#  Giscus 评论系统设置
[params.page.comment.giscus]
category = "" 
categoryId = "" 
darkTheme = "dark" 
emitMetadata = "0" 
enable = false 
inputPosition = "bottom" # top, bottom
lazyLoad = true 
lightTheme = "light" 
mapping = "" 
reactionsEnabled = "1" 
repo = "" 
repoId = "" 
#  第三方库配置
[params.page.library]
[params.page.library.css]
# someCSS = "some.css"
# 位于 "assets/"
# 或者
# someCSS = "https://cdn.example.com/some.css"
[params.page.library.js]
# someJavascript = "some.js"
# 位于 "assets/"
# 或者
# someJavascript = "https://cdn.example.com/some.js"
#  页面 SEO 配置
[params.page.seo]
# 图片 URL
images = []
# 出版者信息
[params.page.seo.publisher]
logoUrl = "/images/avatar.jpg"
name = "Kingpo"

#  TypeIt 配置
[params.typeit]
# 每一步的打字速度（单位是毫秒）
speed = 100
# 光标的闪烁速度（单位是毫秒）
cursorSpeed = 1000
# 光标的字符（支持 HTML 格式）
cursorChar = "|"
# 打字结束之后光标的持续时间（单位是毫秒，"-1" 代表无限大）
duration = -1

#  Mermaid 配置
[params.mermaid]
# 取值详见 https://mermaid-js.github.io/mermaid/#/Setup?id=theme

themes = ['neutral', 'dark']
#  盘古之白配置
[params.pangu]
# 适用于中文写作用户
enable = true

[params.reward] # 文章打赏
alipay = "/images/alipay.png" # 支付宝二维码文件路径
enable = true # true为开启 flase为关闭
wechat = "/images/wechatpay.png" # 微信二维码文件路径

#  水印配置
# 详细参数见 https://github.com/Lruihao/watermark#readme
[params.watermark]
enable = false
# 水印内容（允许 HTML 格式）
content = ''
# 水印透明度
opacity = 0.1
# 水印父节点
appendTo = '.wrapper>main'
# 单水印宽度 单位：px
width = 150
# 单水印高度 单位：px
height = 20
# 水印行间距 单位：px
rowSpacing = 60
# 水印列间距 单位：px
colSpacing = 30
# 水印旋转角度 单位：deg
rotate = 15
# 水印字体大小，单位：rem
fontSize = 0.85
#  水印字体
fontFamily = 'inherit'

#  访问量统计
[params.ibruce]
enable = true
# 在文章中开启
enablePost = true
#   网站创立时间
# 参数 `ibruce.siteTime` 自 v0.2.14 起已弃用，请改用 `footer.siteTime`
# siteTime = '' # 例：'2019-02-03T19:30:34+08:00'
# 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu/360/Sogou
[params.verification]
baidu = ""
bing = ""
google = ""
pinterest = ""
so = ""
sogou = ""
yandex = ""

#  网站 SEO 配置
[params.seo]
# 图片 URL
image = "/site-meta.jpg"
# 缩略图 URL
thumbnailUrl = "/logo.png"

#  网站分析配置
[params.analytics]
enable = true
# Google Analytics
[params.analytics.google]
id = ""
# 是否匿名化用户 IP
anonymizeIP = true
# Fathom Analytics
[params.analytics.fathom]
id = ""
# 自行托管追踪器时的主机路径
server = ""
# Baidu Analytics
# 百度统计
[params.analytics.baidu]
id = "2111c670794ab20de2746cf028182bbb"

#  Cookie 许可配置
[params.cookieconsent]
enable = true
# 用于 Cookie 许可横幅的文本字符串
[params.cookieconsent.content]
dismiss = ""
link = ""
message = ""

#  第三方库文件的 CDN 设置
[params.cdn]
# CDN 数据文件名称，默认不启用
# ("jsdelivr.yml", "unpkg.yml")
# 位于 "themes/FixIt/assets/data/cdn/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件：
# "assets/data/cdn/"
# data = "unpkg.yml"

#  兼容性设置
[params.compatibility]
# 是否使用 Polyfill.io 来兼容旧式浏览器
polyfill = false
# 是否使用 object-fit-images 来兼容旧式浏览器

objectFit = false
#  页面最后添加自定义 JS
# "_custom.js" 位于 "themes/FixIt/assets/js" 目录
# 可以在你的项目下相同路径存放你自己的自定义 JS 文件：
# "assets/js/_custom.js"
[params.customJS]
enable = true
#  在左上角或者右上角显示 GitHub 开源链接
[params.githubCorner]
enable = true 
permalink = "https://github.com/Charlie-king/charlie-king.github.io" 
position = "right" # left, right
title = "在 GitHub 上查看" 
#  Gravatar 设置
[params.gravatar]
# Gravatar 主机，默认：“www.gravatar.com”
host = "www.gravatar.com" # "cn.gravatar.com", "gravatar.loli.net"
style = "mp" # "", mp, identicon, monsterid, wavatar, retro, blank, robohash

# Hugo 解析文档的配置
[markup]
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
################## 必要的配置 ##################
# https://github.com/Lruihao/FixIt/issues/43
codeFences = true
lineNos = true
lineNumbersInTable = true
noClasses = false
################## 必要的配置 ##################
guessSyntax = true
# Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
# 是否在文档中直接使用 HTML 标签
unsafe = true
# 目录设置
[markup.tableOfContents]
endLevel = 6
startLevel = 2

# 作者配置
[author]
email = "zhjin@qq.com"
link = ""
name = "Kingpo"

# 网站地图配置
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks 永久链接配置即文章归属路径设置 (https://gohugo.io/content-management/urls#permalinks)
[Permalinks]
# posts = ":year/:month/:filename"
posts = ":section/:year:month/:filename" #按内容部分/年月/文件名

# 隐私信息配置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

# 
[mediaTypes]
# 用于输出 Markdown 格式文档的设置
[mediaTypes."text/markdown"]
suffixes = ["md"]
# 用于输出 txt 格式文档的设置
[mediaTypes."text/plain"]
suffixes = ["txt"]

# 
[outputFormats]
# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
isHTML = false
isPlainText = true
mediaType = "text/markdown"
#  用于输出 baidu_urls.txt 文件的设置
[outputFormats.BaiduUrls]
baseName = "baidu_urls"
isHTML = false
isPlainText = true
mediaType = "text/plain"
notAlternative = true
#  用于 Hugo 输出文档的设置
[outputs]
home = ["HTML", "RSS", "JSON", "BaiduUrls"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]

[menu]
[[menu.main]]
identifier = "posts"
#  父级菜单项的标识符 (identifier)
parent = ""
# 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
pre = "<i class='fas fa-archive fa-fw fa-sm'></i>"
# 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
name = "文章"
post = ""
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时，将显示的标题
title = "所有文章"
weight = 1
#  向菜单项添加用户定义的内容
[menu.main.params]
# 添加 CSS 类到特定的菜单项
class = "text-center"
# 是否为草稿菜单，类似草稿页面
draft = false

[[menu.main]]
identifier = "categories"
name = "分类"
post = ""
pre = "<i class='fas fa-th fa-fw fa-sm'></i>"
title = ""
url = "/categories/"
weight = 2
[menu.main.params]
# 添加 CSS 类到特定的菜单项
class = "text-center"
# 是否为草稿菜单，类似草稿页面
draft = false

[[menu.main]]
identifier = "tags"
name = "标签"
post = ""
pre = "<i class='fas fa-tags fa-fw fa-sm'></i>"
title = ""
url = "/tags/"
weight = 3
[menu.main.params]
# 添加 CSS 类到特定的菜单项
class = "text-center"
# 是否为草稿菜单，类似草稿页面
draft = false

[[menu.main]]
identifier = "friends"
name = "友链"
post = ""
pre = "<i class='fas fa-users fa-fw fa-sm'></i>"
title = ""
url = "/friends/"
weight = 4
[menu.main.params]
# 添加 CSS 类到特定的菜单项
class = "text-center"
# 是否为草稿菜单，类似草稿页面
draft = false

[[menu.main]]
identifier = "guestbook"
name = "留言"
post = ""
pre = "<i class='fas fa-comments fa-fw fa-sm'></i>"
title = ""
url = "/guestbook/"
weight = 5
[menu.main.params]
# 添加 CSS 类到特定的菜单项
class = "text-center"
# 是否为草稿菜单，类似草稿页面
draft = false

[[menu.main]]
identifier = "about"
name = "关于"
post = ""
pre = "<i class='fas fa-user-tie fa-fw fa-sm'></i>"
title = ""
url = "/about/"
weight = 6
[menu.main.params]
# 添加 CSS 类到特定的菜单项
class = "text-center"
# 是否为草稿菜单，类似草稿页面
draft = false

[[menu.main]]
identifier = "tool"
name = "工具箱"
post = ""
pre = "<i class='fas fa-cube fa-fw fa-sm'></i>"
title = ""
url = "/tool/"
weight = 6
[menu.main.params]
# 添加 CSS 类到特定的菜单项
class = "text-center"
# 是否为草稿菜单，类似草稿页面
draft = false
