name: Generate Contribute List
on:
  push:
    branches:
      - master
    workflow_dispatch:
jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contribute list in contributors.md file
    steps:
      - name: First Contribution Check
        id: first-check
        uses: sukki37/first-contribution-check-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTORS_TOKEN }}
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@master
        if: ${{ steps.first-check.outputs.isNewContributor == 'true' }}
        with:
          readme_path: "contributors.md"
          image_size: 100
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTORS_TOKEN }}
