# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "FixIt"
license = "MIT"
licenselink = "https://github.com/Lruihao/FixIt/blob/master/LICENSE"
description = "A Clean, Elegant but Advanced Hugo Theme for Hugo."
homepage = "https://github.com/Lruihao/FixIt"
tags = [
  "blog",
  "clean",
  "responsive",
  "dark",
  "theme"
]
features = [
  "cover-image",
  "favicon",
  "multilingual",
  "pagination",
  "social-menu",
  "syntax-highlighting",
  "SEO Optimized",
  "friends link template",
  "PWA support",
  "watermark support"
]

[author]
  name = "Lruihao"
  homepage = "https://lruihao.cn"

[original]
  name = "Dillon"
  homepage = "https://dillonzq.com"
  repo = "https://github.com/dillonzq/LoveIt"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.62.0"
