name: Hugo build and deploy
on:
  push:

env:
  TZ: Asia/Shanghai # 设置当前环境时区

jobs:
  Actions-Hugo-Deploy:
    runs-on: ubuntu-latest
    steps:


      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod
     
      - name: Git Configuration
        run: |
          git config --global core.quotePath false
          git config --global core.autocrlf false
          git config --global core.safecrlf true
          git config --global core.ignorecase false
          

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.101.0'
          extended: true
   #   - name: Build Hugo static files
   #     run: hugo --logLevel info --gc --minify
      - name: Build
     #   env:
      #    HUGO_PARAMS_GHTOKEN: ${{ secrets.HUGO_PARAMS_GHTOKEN }}
        run: npm run build
      
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          external_repository: Charlie-king/Charlie-king.github.io
          publish_branch: main
          publish_dir: ./public
#          commit_message: ":rocket: ${{ github.event.head_commit.message }}"
  
      - name: NPM install
        run: npm install
      - name: Update Algolia index
        env:
          ALGOLIA_APP_ID: B6R922P6DD
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: 'dev_hugo'
          ALGOLIA_INDEX_FILE: './public/index.json'
        run: npm run algolia

  
#      - name: Install coscmd
#        run: sudo pip install coscmd
#      - name: Configure coscmd
#        env:
#          COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
#          COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
#          COS_BUCKET_NAME: blog-1256932288
#          COS_BUCKET_REGION: ap-chengdu
#        run: coscmd config -a $COS_SECRET_ID -s $COS_SECRET_KEY -b $COS_BUCKET_NAME -r $COS_BUCKET_REGION
#      - name: Deploy to COS Bucket
#        run: coscmd upload -r -s --delete -f public/ /
